# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0004_auto_20180808_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hoods.Neighbourhood'),
            preserve_default=False,
        ),
    ]
