# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0007_neighbourhood_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='hoods.Neighbourhood'),
        ),
    ]
