# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0009_auto_20180808_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='show_my_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(default='Local business'),
        ),
        migrations.AlterField(
            model_name='business',
            name='neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biashara', to='hoods.Neighbourhood'),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoods.Profile'),
        ),
    ]
