# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0010_auto_20180809_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='health',
            field=models.TextField(default='213'),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police',
            field=models.TextField(default='999'),
        ),
    ]
