# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0012_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='Open',
        ),
    ]
